#!/usr/bin/env bash

set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
sudo stow -v -R --no-folding --ignore '(^|/)README\.md$' -t / -d "$DIR" system || true
stow -v -R --no-folding --ignore '(^|/)README\.md$' -t "$HOME" -d "$DIR" user || true
